<a href="https://colab.research.google.com/github/midhun-craj/ai-ml/blob/main/learning/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

The Basics

In [ ]:
# 1D Array
a = np.array([1, 2, 3], dtype="int64") # We can specify the data type.
print(a)

[1 2 3]


In [ ]:
# 2D Array
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [ ]:
# Get itemsize
print(a.itemsize)
print(b.itemsize)

8
8


In [ ]:
# Get size (no of elements)
print(a.size)
print(b.size)

3
6


In [ ]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)
print(b.nbytes)

24
24
48
