<a href="https://colab.research.google.com/github/midhun-craj/ai-ml/blob/main/learning/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# The Basics

In [ ]:
# 1D Array
a = np.array([1, 2, 3], dtype="int64") # We can specify the data type.
print(a)

[1 2 3]


In [ ]:
# 2D Array
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [ ]:
# Get itemsize
print(a.itemsize)
print(b.itemsize)

8
8


In [ ]:
# Get size (no of elements)
print(a.size)
print(b.size)

3
6


In [ ]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)
print(b.nbytes)

24
24
48


# Accessing/Changing specific elements, rows, columns, etc.

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
# Get a specific element [r, c]
print(a[0, 7])
print(a[1, 3])

8
12


In [ ]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7 8]


In [ ]:
# Get a specific column
print(a[:, 3])

[ 4 12]


In [ ]:
# Getting a little more fancy [startIndex:endIndex:stepSize]
print(a[1, 0:8:2])
print(a[0:2, 3])

[ 9 11 13 15]
[ 4 12]


In [ ]:
a[1, 0] = 20
print(a)

[[ 1  2  3  4  5  6  7  8]
 [20 10 11 12 13 14 15 16]]


In [ ]:
# a[1, :] = 24
# print(a)

a[:, 0] = 24
print(a)

[[24  2  3  4  5  6  7  8]
 [24 24 24 24 24 24 24 24]]


## 3D - example

In [ ]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
print(b[1, 0, 0])
print(b[0, 0, 0])

5
1


In [ ]:
print(b[:, 1, :])
print("--------")
print(b[:, 0, :])

[[3 4]
 [7 8]]
--------
[[1 2]
 [5 6]]


In [ ]:
# Replace
b[1, 0, 1] = 20
print(b)

[[[20 20]
  [ 3  4]]

 [[ 5 20]
  [20  8]]]


In [ ]:
b[0, 1, :] = [22, 22]
print(b)

[[[20 20]
  [22 22]]

 [[22 22]
  [20  8]]]


# Initializing different types of arrays

In [ ]:
# All 0s matrix
a = np.zeros((2, 3), dtype='int16')
print(a)

[[0 0 0]
 [0 0 0]]


In [ ]:
# All 1s matrix
a = np.ones((2, 3), dtype='int32')
print(a)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Any other number
a = np.full((2, 8), 24, dtype='float32')
print(a)

[[24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24.]]


In [ ]:
# Any other number (full_like) using existing shape

# print(np.full(a.shape, 9, dtype='float32'))

a = np.full_like(a, 4, dtype='int32')
print(a)

[[4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4]]


In [ ]:
# Random decimal numbers
a = np.random.rand(4, 4)
print(a)

[[0.50403085 0.79279364 0.15044094 0.79671797]
 [0.38292142 0.16883175 0.53220185 0.56486473]
 [0.38080173 0.64297718 0.46073012 0.30307505]
 [0.67007834 0.85018137 0.32924329 0.60780991]]


In [ ]:
# Random decimal numbers (random_sample) using existing shape
a = np.random.random_sample(a.shape)
print(a)

[[0.1582247  0.92677152 0.96813889 0.30303848]
 [0.97118194 0.64314859 0.81432786 0.95430525]
 [0.19855773 0.5558884  0.59426841 0.95398429]
 [0.63435853 0.39723136 0.75041432 0.78045347]]


In [ ]:
# Random integer values
a = np.random.randint(2, 8, size=(4, 4), dtype='int64')
print(a)

[[2 6 5 3]
 [2 6 4 6]
 [7 4 4 7]
 [2 7 2 2]]


In [ ]:
# The identity matrix
a = np.identity(2, dtype='bool')
print(a)

[[ True False]
 [False  True]]


In [ ]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
# Task
output = np.ones((5, 5), dtype='int32')
print(output)

print('--------------------')

z = np.zeros((3, 3), dtype='int32')
z[1, 1] = 9
print(z)

print('--------------------')

output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
--------------------
[[0 0 0]
 [0 9 0]
 [0 0 0]]
--------------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Be careful when copying arrays!!!

In [89]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [3]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [102]:
print(a + 2)

[3 4 5 6]


In [103]:
print(a - 2)

[-1  0  1  2]


In [104]:
print(a / 2)

[0.5 1.  1.5 2. ]


In [105]:
print(a * 2)

[2 4 6 8]


In [11]:
b = np.array([1, 0, 1, 0])
print(a + b)
print(a * b)

[2 2 4 4]
[1 0 3 0]


In [5]:
print(a ** 2)

[ 1  4  9 16]


In [10]:
print(np.sin(a)) # Take the sin
print(np.cos(a)) # Take the cos
print(np.tan(a)) # Take the tan

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [16]:
# Matrix Multiplication
a = np.ones((2, 3))
print(a)

print('----------')

b = np.full((3, 2), 2)
print(b)

print('----------')

print(np.matmul(a, b))
print(np.matmul(b, a))

[[1. 1. 1.]
 [1. 1. 1.]]
----------
[[2 2]
 [2 2]
 [2 2]]
----------
[[6. 6.]
 [6. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [19]:
# Find the determinant
a = np.identity(3)
print(a)
print('----------')
print(np.linalg.det(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
1.0


# Statistics

In [2]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [7]:
# Min
print(np.min(stats))
print(np.min(stats, axis=1))
print(np.min(stats, axis=0))

1
[1 4]
[1 2 3]


In [9]:
# Max
print(np.max(stats))
print(np.max(stats, axis=1))
print(np.max(stats, axis=0))

6
[3 6]
[4 5 6]


In [13]:
# Sum
print(np.sum(stats))
print(np.sum(stats, axis=1))
print(np.sum(stats, axis=0))

21
[ 6 15]
[5 7 9]


# Reorganizing Arrays

In [21]:
# Reshape
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)
print(before)

print('----------')

after = before.reshape((2, 2, 2))
print(after.shape)
print(after)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
----------
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

print(np.vstack((v1, v2, v1, v2)))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [31]:
# Horizontally stacking vectors
h1 = np.ones((2, 3))
h2 = np.zeros((2, 2))

print(np.hstack((h1, h2, h1)))

[[1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]]


# Miscellaneous

## Load data from file

In [57]:
data = np.genfromtxt('data.txt', delimiter=',')
# print(data)

# print()
# print()

# print(data.astype('int32')) # astype only copies the data

data = data.astype('int32')

print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and Advanced Indexing

In [62]:
data > 50
print()
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [63]:
# You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[[1, 2, 8]])

[2 3 9]


In [71]:
print(np.any(data > 50, axis=0))
print()
print(np.all(data > 50, axis=0))
print()
print(np.any(data > 50, axis=1))
print()
print(np.all(data > 50, axis=1))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]

[False False False False  True False False False False False False False
 False False False False False False]

[ True  True  True]

[False False False]


In [77]:
print(((data > 50) & (data < 100)))
print()
print((~((data > 50) & (data < 100))))

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
